version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: lumileds-mysql
        working_dir: /opt/lumileds
        volumes:
            - .:/opt/lumileds
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${DOCKER_MYSQL_PORT}:3306

    webserver:
        image: nginx:alpine
        container_name: lumileds-webserver
        working_dir: /opt/lumileds
        depends_on:
            - php
        volumes:
            - .:/opt/lumileds
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${DOCKER_WEBSERVER_PORT}:80

    php:
        build: docker/dev/php
        container_name: lumileds-php
        working_dir: /opt/lumileds
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - RABBITMQ_HOST=${RABBITMQ_HOST}
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_PREFIX=${RABBITMQ_PREFIX}
            - COMPOSER_ALLOW_SUPERUSER=1
            - XDEBUG_CONFIG=idekey=PHPSTORM
            - PHP_IDE_CONFIG=serverName=lumileds
        depends_on:
            - mysql
        volumes:
            - .:/opt/lumileds

    node:
        build: docker/dev/node
        container_name: lumileds-node
        working_dir: /opt/lumileds
        volumes:
            - .:/opt/lumileds

    rabbitmq:
        image: rabbitmq:3-management
        container_name: lumileds-rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        ports:
            - ${DOCKER_RABBITMQ_API_PORT}:15672
            - ${DOCKER_RABBITMQ_PORT}:5672
        volumes:
            - ./docker/dev/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - 1025:1025
            - 8025:8025
