up:
	docker-compose up -d

rebuild:
	docker-compose up -d --build --force-recreate

down:
	docker-compose down

stop:
	docker-compose stop

enter_php:
	docker-compose exec php bash

enter_node:
	docker-compose exec node sh

ps:
	docker-compose ps

logs:
	docker-compose logs -f
